# The link contract of the coverage callbacks (src/checkpoint.c, README.md).
# Usage: cmake -DNM=<nm> -DLIBRARY=<archive> -DENABLED=<ON|OFF> -P check_coverage_references.cmake
# A COVERAGE archive (ENABLED) refers to each callback as an ordinary undefined
# symbol and defines none of them, not even weakly: a program linked without a
# provider such as libhfuzz fails to link, and a provider archive listed after
# this one is extracted for them. An ordinary archive refers to none of them.
set(CALLBACKS hfuzz_trace_pc __sanitizer_cov_trace_pc_guard_init __sanitizer_cov_trace_pc_guard)
execute_process(COMMAND "${NM}" -A -P "${LIBRARY}"
                OUTPUT_VARIABLE symbols RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "${NM} failed on ${LIBRARY}")
endif()
string(REPLACE "\n" ";" lines "${symbols}")
set(rows 0)
set(control OFF)
foreach(callback IN LISTS CALLBACKS)
    set(classes_${callback})
endforeach()
foreach(line IN LISTS lines)
    # POSIX format with the member: "ARCHIVE[MEMBER]: NAME CLASS [VALUE [SIZE]]".
    if(NOT line MATCHES "^.*\\]: ([^ ]+) ([A-Za-z?-])( |$)")
        continue()
    endif()
    math(EXPR rows "${rows} + 1")
    set(name "${CMAKE_MATCH_1}")
    set(class "${CMAKE_MATCH_2}")
    # A control, so that a listing this script cannot read fails instead of passing.
    if(name STREQUAL "restore_checkpoint" AND class STREQUAL "T")
        set(control ON)
    endif()
    list(FIND CALLBACKS "${name}" index)
    if(NOT index EQUAL -1)
        list(APPEND classes_${name} "${class}")
    endif()
endforeach()
if(rows EQUAL 0 OR NOT control)
    message(FATAL_ERROR "${LIBRARY}: no readable symbol rows (or no defined restore_checkpoint) in the output of ${NM}")
endif()
set(problems)
foreach(callback IN LISTS CALLBACKS)
    set(classes "${classes_${callback}}")
    if(ENABLED)
        list(REMOVE_DUPLICATES classes)
        if(NOT classes STREQUAL "U")
            list(APPEND problems "${callback}: classes '${classes}', expected only U (strong undefined)")
        endif()
    elseif(classes)
        list(APPEND problems "${callback}: classes '${classes}' in an archive without coverage")
    endif()
endforeach()
if(problems)
    string(REPLACE ";" "\n  " problems "${problems}")
    message(FATAL_ERROR "${LIBRARY}:\n  ${problems}")
endif()
if(ENABLED)
    message(STATUS "${LIBRARY}: the coverage callbacks are strong undefined references")
else()
    message(STATUS "${LIBRARY}: no coverage callback references")
endif()
