# Fail closed if either private scratch object is no longer local NOBITS.
execute_process(COMMAND "${READELF}" -SW "${BINARY}"
                OUTPUT_VARIABLE sections RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "cannot inspect startup storage sections")
endif()
string(REGEX MATCH "\\[[ ]*([0-9]+)\\][ \t]+teapot_protected_bss[ \t]+NOBITS[ \t]" found "${sections}")
if(NOT found)
    message(FATAL_ERROR "protected startup storage is not NOBITS")
endif()
set(bss_index "${CMAKE_MATCH_1}")
execute_process(COMMAND "${READELF}" -sW "${BINARY}"
                OUTPUT_VARIABLE symbols RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "cannot inspect startup storage symbols")
endif()
foreach(name IN ITEMS startup_maps proc_buffer)
    string(REGEX MATCH "[ \t]([0-9a-fA-F]+)[ \t]+([0-9a-fA-Fx]+)[ \t]+OBJECT[ \t]+LOCAL[ \t]+HIDDEN[ \t]+${bss_index}[ \t]+${name}[\r\n]"
           found "${symbols}")
    if(NOT found)
        message(FATAL_ERROR "${name} is not a local hidden object in protected NOBITS storage")
    endif()
    math(EXPR alignment "0x${CMAKE_MATCH_1} % 8")
    math(EXPR size "${CMAKE_MATCH_2}")
    set(expected 4096)
    if(name STREQUAL "startup_maps")
        set(expected 196608)
    endif()
    if(NOT alignment EQUAL 0 OR NOT size EQUAL expected)
        message(FATAL_ERROR "${name}: invalid alignment or size ${size}")
    endif()
endforeach()
message(STATUS "both private startup buffers are local hidden, correctly sized/aligned protected NOBITS objects")
