# Compare both executions, never convert a failure/timeout into an expected pass.
if(NOT DEFINED PROGRAM OR NOT EXISTS "${PROGRAM}")
    message(FATAL_ERROR "Missing RISC rollback executable")
endif()
foreach(name IN ITEMS NESTED REPLAY MAPPED)
    if(NOT DEFINED ${name} OR NOT "${${name}}" MATCHES "^[01]$")
        message(FATAL_ERROR "Invalid rollback fixture argument ${name}")
    endif()
endforeach()
foreach(enabled IN ITEMS 0 1)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "TEAPOT_FAULT_ADAPTATION=${enabled}"
        ${EMULATOR} "${PROGRAM}" "${NESTED}" "${REPLAY}" "${MAPPED}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 25)
    if(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "RISC rollback adaptation=${enabled} failed (${status})\n${output}\n${error}")
    endif()
    if(NOT output MATCHES "instruction-count=17 PASS")
        message(FATAL_ERROR "RISC rollback fixture did not reach its assertions: ${output}")
    endif()
    if(enabled EQUAL 0)
        set(disabled_output "${output}")
    elseif(NOT "${output}" STREQUAL "${disabled_output}")
        message(FATAL_ERROR "RISC rollback ON/OFF differs\nOFF:${disabled_output}\nON:${output}")
    endif()
endforeach()
message(STATUS "${output}")
