#pragma once

/* Shared with Python instrumentation. Use decimal literals without leading zeroes. */
#define AARCH64_SHADOW_STACK_SIZE 8388608
#define AARCH64_SHADOW_STACK_DIFT_OFFSET 0
#define AARCH64_SHADOW_STACK_MEMLOG_OFFSET 64
#define AARCH64_SHADOW_STACK_ASAN_OFFSET 128
#define AARCH64_SHADOW_STACK_GADGET_MEM_OFFSET 192
#define AARCH64_SHADOW_STACK_GADGET_PORT_OFFSET 240
#define AARCH64_SHADOW_STACK_COVERAGE_OFFSET 288
#define AARCH64_SHADOW_STACK_CONTROL_OFFSET 320
#define AARCH64_SHADOW_STACK_RESTORE_OFFSET 352
#define AARCH64_SHADOW_STACK_INDIRECT_TARGET_OFFSET 384
#define AARCH64_SHADOW_STACK_REPORT_OFFSET 416
#define AARCH64_SHADOW_STACK_ABI_OFFSET 448
#define AARCH64_SHADOW_STACK_TEXT_DIFT_CAPTURE_OFFSET 480
#define AARCH64_SHADOW_STACK_TEXT_DIFT_LLVM_OFFSET 512

#if AARCH64_SHADOW_STACK_SIZE < 4096 || AARCH64_SHADOW_STACK_SIZE % 4096 != 0 || \
    (AARCH64_SHADOW_STACK_SIZE >> 12) > 4095
#error "AArch64 shadow stack size must be 1-4095 pages for one add/sub immediate"
#endif

#if AARCH64_SHADOW_STACK_CONTROL_OFFSET < 0 || AARCH64_SHADOW_STACK_CONTROL_OFFSET > 504 || \
    AARCH64_SHADOW_STACK_CONTROL_OFFSET % 8 != 0 || \
    AARCH64_SHADOW_STACK_REPORT_OFFSET < 0 || AARCH64_SHADOW_STACK_REPORT_OFFSET > 504 || \
    AARCH64_SHADOW_STACK_REPORT_OFFSET % 8 != 0
#error "AArch64 control/report shadow stack offsets must fit a register-pair immediate"
#endif
