function(teapot_validate_dift_layout name xor_mask asan_offset)
    # Both shadow mapping and MTE initialization currently consume ranges 0–4.
    # Reject unsupported layouts instead of silently omitting their tail.
    list(LENGTH ARGN range_count)
    if(range_count GREATER 5)
        message(FATAL_ERROR "DIFT layout ${name} has ${range_count} app ranges; the runtime supports at most 5")
    endif()
    math(EXPR granularity "${xor_mask} & -${xor_mask}")
    if(granularity LESS_EQUAL 0)
        message(FATAL_ERROR "DIFT layout ${name} has an invalid XOR mask")
    endif()

    set(app_ranges)
    set(shadow_ranges)
    foreach(range IN LISTS ARGN)
        string(REPLACE ":" ";" bounds "${range}")
        list(LENGTH bounds count)
        if(NOT count EQUAL 2)
            message(FATAL_ERROR "Invalid app range ${range} in DIFT layout ${name}")
        endif()
        list(GET bounds 0 start)
        list(GET bounds 1 end)
        if(start LESS 0 OR start GREATER_EQUAL end)
            message(FATAL_ERROR "Invalid app range ${range} in DIFT layout ${name}")
        endif()
        foreach(previous IN LISTS app_ranges)
            string(REPLACE ":" ";" bounds "${previous}")
            list(GET bounds 0 previous_start)
            list(GET bounds 1 previous_end)
            if(start LESS previous_end AND previous_start LESS end)
                message(FATAL_ERROR "DIFT layout ${name} app ranges overlap")
            endif()
        endforeach()
        list(APPEND app_ranges "${range}")

        # XOR is monotone only within chunks delimited by its lowest set bit.
        set(cursor "${start}")
        while(cursor LESS end)
            math(EXPR next "(${cursor} / ${granularity} + 1) * ${granularity}")
            if(next GREATER end)
                set(next "${end}")
            endif()
            math(EXPR shadow_start "${cursor} ^ ${xor_mask}")
            math(EXPR shadow_end "((${next} - 1) ^ ${xor_mask}) + 1")
            list(APPEND shadow_ranges "${shadow_start}:${shadow_end}")
            set(cursor "${next}")
        endwhile()
    endforeach()

    foreach(shadow IN LISTS shadow_ranges)
        string(REPLACE ":" ";" bounds "${shadow}")
        list(GET bounds 0 shadow_start)
        list(GET bounds 1 shadow_end)
        foreach(app IN LISTS app_ranges)
            string(REPLACE ":" ";" bounds "${app}")
            list(GET bounds 0 start)
            list(GET bounds 1 end)
            if(shadow_start LESS end AND start LESS shadow_end)
                message(FATAL_ERROR "DIFT layout ${name} tag and app ranges overlap")
            endif()
            math(EXPR asan_start "(${start} >> 3) + ${asan_offset}")
            math(EXPR asan_end "((${end} - 1) >> 3) + ${asan_offset} + 1")
            if(shadow_start LESS asan_end AND asan_start LESS shadow_end)
                message(FATAL_ERROR "DIFT layout ${name} tag and ASan ranges overlap")
            endif()
        endforeach()
    endforeach()
endfunction()
