if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
endif()

set(CHECKPOINT_ARCH "" CACHE STRING "Target architecture override for libcheckpoint")
set(TEAPOT_DIFT_LAYOUT "" CACHE STRING "Teapot DIFT layout profile")
set(TEAPOT_AARCH64_TAG_STORAGE "shadow" CACHE STRING "AArch64 Teapot ASan-style tag storage backend: shadow or mte")

option(TEAPOT_ENABLE_DIFT_RUNTIME "Enable libcheckpoint DIFT shadow initialization" ON)
set(_coverage_default OFF)
if(CMAKE_C_COMPILER MATCHES "hfuzz")
    set(_coverage_default ON)
endif()
option(TEAPOT_ENABLE_COVERAGE "Enable honggfuzz coverage callbacks" ${_coverage_default})
set(TEAPOT_X64_VECTOR_STATE "auto" CACHE STRING "Checkpoint vector state: auto, xmm0-7, sse, avx, full")
set_property(CACHE TEAPOT_X64_VECTOR_STATE PROPERTY STRINGS auto xmm0-7 sse avx full)
# The index is TEAPOT_X64_VECTOR_MODE: 0 keeps each checkpoint site's choice,
# 1-4 are the LIBCHECKPOINT_X64_VECTOR_* values of checkpoint.h.
set(_vector_modes auto xmm0-7 sse avx full)
list(FIND _vector_modes "${TEAPOT_X64_VECTOR_STATE}" _vector_mode)
if(_vector_mode EQUAL -1)
    message(FATAL_ERROR "Unsupported TEAPOT_X64_VECTOR_STATE=${TEAPOT_X64_VECTOR_STATE}")
endif()
option(TEAPOT_ENABLE_RISCV_FLOAT_STATE "Save and restore RISC-V floating-point registers and FCSR" OFF)
option(TEAPOT_BUILD_NESTED_RUNTIME "Build the nested-speculation checkpoint_nested runtime target" OFF)
option(TEAPOT_BUILD_DIFT_MATH_WRAPPERS "Build optional DIFT wrappers for libm functions" OFF)
option(TEAPOT_BUILD_DIFT_ZLIB_WRAPPERS "Build optional DIFT wrappers for zlib functions" OFF)
option(TEAPOT_EXPERIMENTAL_AARCH64_BTI "Enable the page-isolated AArch64 BTI experiment" OFF)
